# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


hash_careers = {
  "SPCG" => "Communication Grad",
  "CNED" => "Continuing Education",
  "CGRD" => "Continuing Education Grad",
  "CNCR" => "Continuing Noncredit",
  "EDG"  => "Education Grad",
  "MGMT" => "J L Kellogg School Management",
  "JRNG" => "Journalism Grad",
  "EMP"  => "Kellogg Executive Masters Prog",
  "LAW"  => "Law",
  "ENGG" => "McCormick Engg Grad",
  "MUSG" => "Music Grad",
  "NDGR" => "Non-Degree",
  "PT" => "Physical Therapy",
  "PA" => "Physician Assistant",
  "PO" => "Prosthetics Orthotics",
  "TGS" => "The Graduate School",
  "UGRD" => "Undergraduate",
}

hash_careers.each { |key, value|
    Career.create :id => key, :title => value
}

hash_departments = {
    "ACCOUNT" => "ACCOUNT - Accounting",
    "ACCT" => "ACCT - Accounting & Info Systems",
    "ACCTX" => "ACCTX - Accounting & Info Systems",
    "ADVT" => "ADVT - Advertising",
    "AFST" => "AFST - African Studies",
    "AF_AM_ST" => "AF_AM_ST - African American Studies",
    "ALT_CERT" => "ALT_CERT - Alternative Certification",
    "AMER_ST" => "AMER_ST - American Studies",
    "AMES" => "AMES - Asian & Middle Eastern Studies",
    "ANTHRO" => "ANTHRO - Anthropology",
    "APP_PHYS" => "APP_PHYS - Applied Physics",
    "ARABIC" => "ARABIC - Arabic",
    "ART" => "ART - Art Theory & Practice",
    "ART_HIST" => "ART_HIST - Art History",
    "ASIAN_AM" => "ASIAN_AM - Asian American Studies",
    "ASTRON" => "ASTRON - Astronomy",
    "BIOL_SCI" => "BIOL_SCI - Biological Sciences",
    "BLAW" => "BLAW - Business Law",
    "BMD_ENG" => "BMD_ENG - Biomedical Engineering",
    "BUS_ALYS" => "BUS_ALYS - Business Analyst",
    "BUS_INST" => "BUS_INST - Business Institutions",
    "BUS_LAW" => "BUS_LAW - Business Law",
    "CFS" => "CFS - Chicago Field Studies",
    "CHEM" => "CHEM - Chemistry",
    "CHEM_ENG" => "CHEM_ENG - Chemical Engineering",
    "CHINESE" => "CHINESE - Chinese",
    "CHSS" => "CHSS - Comp & Hist Social Science",
    "CIC" => "CIC - CIC Traveling Scholar",
    "CIS" => "CIS - Computer Information Systems",
    "CIV_ENV" => "CIV_ENV - Civil & Envrnmtl Engineering",
    "CLASSICS" => "CLASSICS - Classics - Readings in Englis",
    "CLIN_PSY" => "CLIN_PSY - Clinical Psychology",
    "CLIN_RES" => "CLIN_RES - Clinical Research & Reg Admin",
    "CME" => "CME - Chicago Metropolitan Exchange",
    "CMN" => "CMN - Communication Related Courses",
    "COG_SCI" => "COG_SCI - Cognitive Science",
    "COMM_ST" => "COMM_ST - Communication Studies",
    "COMP_LIT" => "COMP_LIT - Comparative Literary Studies",
    "CONDUCT" => "CONDUCT - Conducting",
    "COUN_PSY" => "COUN_PSY - Counseling Psychology",
    "CRDV" => "CRDV - Career Development",
    "CSD" => "CSD - Comm Sci & Disorders",
    "DANCE" => "DANCE - Dance",
    "DECS" => "DECS - Mngrl Econ & Decision Sci",
    "DECSX" => "DECSX - Mngrl Econ & Decision Sci",
    "DIV_MED" => "DIV_MED - Divorce Mediation Training",
    "DSGN" => "DSGN - Segal Design Institute",
    "EARTH" => "EARTH - Earth and Planetary Sciences",
    "ECON" => "ECON - Economics",
    "EECS" => "EECS - Elect Engineering & Comp Sci",
    "ENGLISH" => "ENGLISH - English",
    "ENTR" => "ENTR - Entrepreneurship",
    "ENVR_POL" => "ENVR_POL - Environmental Policy & Culture",
    "ENVR_SCI" => "ENVR_SCI - Environmental Science",
    "EPI_BIO" => "EPI_BIO - Epidemiology & Biostats",
    "ES_APPM" => "ES_APPM - Engineering Sci & Applied Mat",
    "EXMMX" => "EXMMX - Executive Master in Management",
    "FINANCE" => "FINANCE - Finance",
    "FINC" => "FINC - Finance",
    "FINCX" => "FINCX - Finance",
    "FN_EXTND" => "FN_EXTND - CFP Extended",
    "FRENCH" => "FRENCH - French",
    "GBL_HLTH" => "GBL_HLTH - Global Health",
    "GENET_CN" => "GENET_CN - Genetic Counseling",
    "GEN_CMN" => "GEN_CMN - General Comm & Intro Courses",
    "GEN_ENG" => "GEN_ENG - General Engineering",
    "GEN_LA" => "GEN_LA - General Liberal Arts",
    "GEN_MUS" => "GEN_MUS - General Music",
    "GEOG" => "GEOG - Geography",
    "GERMAN" => "GERMAN - German",
    "GNDR_ST" => "GNDR_ST - Gender Studies",
    "GREEK" => "GREEK - Greek",
    "HDPS" => "HDPS - Human Develop & Psych Svcs",
    "HDSP" => "HDSP - Human Development & Social Pol",
    "HEBREW" => "HEBREW - Hebrew",
    "HEMA" => "HEMA - Health Enterprise Management",
    "HINDI" => "HINDI - Hindi",
    "HISTORY" => "HISTORY - History",
    "HQS" => "HQS - Hlthcare Quality & Pat Safety",
    "HSR" => "HSR - Health Services Research",
    "HUM" => "HUM - Humanities",
    "IBIS" => "IBIS - Interdepartmental Bio Sciences",
    "IEMS" => "IEMS - Indust Eng & Mgmt Sciences",
    "IGP" => "IGP - Integ Life Sciences",
    "IMC" => "IMC - Integ Marketing Communication",
    "INF_TECH" => "INF_TECH - Information Technology",
    "INTG_SCI" => "INTG_SCI - Integrated Science",
    "INTL" => "INTL - International Business",
    "INTLX" => "INTLX - International Business",
    "INTL_ST" => "INTL_ST - International Studies",
    "IPLS" => "IPLS - Liberal Studies",
    "ISEN" => "ISEN - Initiative Sustain & Energy",
    "ITALIAN" => "ITALIAN - Italian",
    "JAPANESE" => "JAPANESE - Japanese",
    "JAZZ_ST" => "JAZZ_ST - Jazz Studies",
    "JOUR" => "JOUR - Journalism",
    "JRN_WRIT" => "JRN_WRIT - Journalistic Writing",
    "JWSH_ST" => "JWSH_ST - Jewish Studies",
    "JW_LEAD" => "JW_LEAD - Jewish Leadership",
    "KELLG_FE" => "KELLG_FE - Financial Economics",
    "KELLG_MA" => "KELLG_MA - Managerial Analytics",
    "KOREAN" => "KOREAN - Korean",
    "LATIN" => "LATIN - Latin",
    "LATINO" => "LATINO - Latina and Latino Studies",
    "LAWSTUDY" => "LAWSTUDY - Law Studies",
    "LDRSHP" => "LDRSHP - Leadership",
    "LEADERS" => "LEADERS - Leadership",
    "LEAD_ART" => "LEAD_ART - Art of Leadership",
    "LEGAL_ST" => "LEGAL_ST - Legal Studies",
    "LING" => "LING - Linguistics",
    "LIT" => "LIT - Literature",
    "LITARB" => "LITARB - Litigation and Arbitration",
    "LOC" => "LOC - Learning & Org Change",
    "LRN_SCI" => "LRN_SCI - Learning Sciences",
    "MATH" => "MATH - Mathematics",
    "MAT_SCI" => "MAT_SCI - Materials Science & Eng",
    "MBIOTECH" => "MBIOTECH - Masters in Biotechnology",
    "MCW" => "MCW - Master of Creative Writing",
    "MDVL_ST" => "MDVL_ST - Medieval Studies",
    "MECH_ENG" => "MECH_ENG - Mechanical Engineering",
    "MECN" => "MECN - Decision Sciences",
    "MECNX" => "MECNX - Decision Sciences",
    "MECS" => "MECS - Managerial Econ & Strategy",
    "MECSX" => "MECSX - Managerial Econ & Strategy",
    "MEDM" => "MEDM - Media Management",
    "MED_INF" => "MED_INF - Medical Informatics",
    "MED_SKIL" => "MED_SKIL - Mediation Skills Training",
    "MGMT" => "MGMT - Management",
    "MGMTX" => "MGMTX - Management",
    "MHB" => "MHB - Medical Humanities & Bioethics",
    "MKTG" => "MKTG - Marketing",
    "MKTGX" => "MKTGX - Marketing",
    "MMSS" => "MMSS - Math Methods in the Social Sc",
    "MORS" => "MORS - Management and Organizations",
    "MORSX" => "MORSX - Management and Organizations",
    "MPD" => "MPD - Master of Product Development",
    "MPPA" => "MPPA - Master of Public Policy Admin",
    "MSA" => "MSA - Sports Administration",
    "MSC" => "MSC - MS in Communication",
    "MSCI" => "MSCI - Master of Science in Clin Inv",
    "MSIA" => "MSIA - Master of Science in Analytics",
    "MSRC" => "MSRC - Master of Regulatory Complianc",
    "MSTP" => "MSTP - Medical Scientist Training",
    "MS_ED" => "MS_ED - MS in Educ & Social Policy",
    "MS_FT" => "MS_FT - MS in Marital & Family Therapy",
    "MS_HE" => "MS_HE - MS in Higher Ed Admin & Policy",
    "MS_LOC" => "MS_LOC - Learning & Org Change",
    "MTS" => "MTS - Media, Technology & Society",
    "MUSEUM" => "MUSEUM - Museum Studies",
    "MUSIC" => "MUSIC - Music",
    "MUSICOL" => "MUSICOL - Musicology",
    "MUSIC_ED" => "MUSIC_ED - Music Education",
    "MUS_COMP" => "MUS_COMP - Music Composition",
    "MUS_HIST" => "MUS_HIST - Music History & Lit",
    "MUS_TECH" => "MUS_TECH - Music Technology",
    "MUS_THRY" => "MUS_THRY - Music Theory",
    "NAV_SCI" => "NAV_SCI - Naval Science",
    "NEUROBIO" => "NEUROBIO - Neurobiology & Physiology",
    "NUIN" => "NUIN - Neuroscience",
    "OPNS" => "OPNS - Operations Management",
    "OPNSX" => "OPNSX - Operations Management",
    "ORG_BEH" => "ORG_BEH - Organizational Behavior",
    "ORTH" => "ORTH - Orthotics",
    "PBC" => "PBC - Plant Biology & Conservation",
    "PERF_ST" => "PERF_ST - Performance Studies",
    "PERSIAN" => "PERSIAN - Persian",
    "PHIL" => "PHIL - Philosophy",
    "PHIL_NP" => "PHIL_NP - Philanthropy & Nonprofit Fund",
    "PHYSICS" => "PHYSICS - Physics",
    "PHYS_TH" => "PHYS_TH - Physical Therapy",
    "PIANO" => "PIANO - Piano",
    "POLI_SCI" => "POLI_SCI - Political Science",
    "PORT" => "PORT - Portuguese",
    "PREDICT" => "PREDICT - Predictive Analytics",
    "PROJ_MGT" => "PROJ_MGT - Project Management",
    "PROJ_PMI" => "PROJ_PMI - Project Management",
    "PROS" => "PROS - Prosthetics",
    "PSYCH" => "PSYCH - Psychology",
    "PUB_HLTH" => "PUB_HLTH - Master's in Public Health",
    "QARS" => "QARS - Qual Assur & Reg Science",
    "REAL" => "REAL - Real Estate",
    "RELIGION" => "RELIGION - Religious Studies",
    "RTVF" => "RTVF - Radio/Television/Film",
    "SCS" => "SCS - School of Continuing Studies",
    "SEEK" => "SEEK - Social Enterprise",
    "SESP" => "SESP - SESP Core",
    "SHC" => "SHC - Science in Human Culture",
    "SLAVIC" => "SLAVIC - Slavic Languages & Literature",
    "SOCIOL" => "SOCIOL - Sociology",
    "SOC_POL" => "SOC_POL - Social Policy",
    "SPANISH" => "SPANISH - Spanish",
    "SPANPORT" => "SPANPORT - Spanish and Portuguese",
    "STAT" => "STAT - Statistics",
    "STRINGS" => "STRINGS - String Instruments",
    "SWAHILI" => "SWAHILI - Swahili",
    "TEACH_ED" => "TEACH_ED - Teacher Education",
    "TGS" => "TGS - TGS General Registrations",
    "TH&DRAMA" => "TH&DRAMA - Theatre & Drama",
    "THEATRE" => "THEATRE - Theatre",
    "TURKISH" => "TURKISH - Turkish",
    "URBAN_ST" => "URBAN_ST - Urban Studies",
    "VOICE" => "VOICE - Voice & Opera",
    "WIND_PER" => "WIND_PER - Wind & Percussion",
    "WRITING" => "WRITING - Writing Arts",
}    

hash_departments.each { |key, value|
    Department.create :id => key, :title => value
}

hash_terms = {
    "4000" => ["2000 Fall", "2000-01"],
    "4005" => ["2000-01 Academic Year", "2000-01"],
    "4010" => ["2001 Winter", "2000-01"],
    "4020" => ["2001 Spring", "2000-01"],
    "4030" => ["2001 Summer", "2000-01"],

    "4040" => ["2001 Fall", "2001-02"],
    "4045" => ["2001-02 Academic Year","2001-02"],
    "4050" => ["2002 Winter", "2001-02"],
    "4060" => ["2002 Spring", "2001-02"],
    "4070" => ["2002 Summer", "2001-02"],

    "4080" => ["2002 Fall","2002-03"],
    "4085" => ["2002-03 Academic Year", "2002-03"],
    "4090" => ["2003 Winter","2002-03"],
    "4100" => ["2003 Spring","2002-03"],
    "4110" => ["2003 Summer","2002-03"],

    "4120" => ["2003 Fall","2003-04"],
    "4125" => ["2003-04 Academic Year", "2003-04"],
    "4130" => ["2004 Winter","2003-04"],
    "4140" => ["2004 Spring","2003-04"],
    "4150" => ["2004 Summer","2003-04"],

    "4160" => ["2004 Fall","2004-05"],
    "4165" => ["2004-05 Academic Year", "2004-05"],
    "4170" => ["2005 Winter","2004-05"],
    "4180" => ["2005 Spring","2004-05"],
    "4190" => ["2005 Summer","2004-05"],

    "4200" => ["2005 Fall","2004-05"],
    "4205" => ["2005-06 Academic Year", "2004-05"],
    "4210" => ["2006 Winter","2004-05"],
    "4220" => ["2006 Spring","2004-05"],
    "4230" => ["2006 Summer","2004-05"],

    "4240" => ["2006 Fall", "2005-06"],
    "4245" => ["2006-07 Academic Year", "2005-06"],
    "4250" => ["2007 Winter", "2005-06"],
    "4260" => ["2007 Spring", "2005-06"],
    "4270" => ["2007 Summer", "2005-06"],

    "4280" => ["2007 Fall", "2007-08"],
    "4285" => ["2007-08 Academic Year","2007-08"],
    "4290" => ["2008 Winter","2007-08"],
    "4300" => ["2008 Spring","2007-08"],
    "4310" => ["2008 Summer","2007-08"],

    "4320" => ["2008 Fall","2008-09"],
    "4325" => ["2008-09 Academic Year","2008-09"],
    "4330" => ["2009 Winter","2008-09"],
    "4340" => ["2009 Spring","2008-09"],
    "4350" => ["2009 Summer","2008-09"],

    "4360" => ["2009 Fall","2009-10"],
    "4365" => ["2009-10 Academic Year","2009-10"],
    "4370" => ["2010 Winter","2009-10"],
    "4380" => ["2010 Spring","2009-10"],
    "4390" => ["2010 Summer","2009-10"],

    "4400" => ["2010 Fall","2010-11"],
    "4405" => ["2010-2011 Academic Year","2010-11"],
    "4410" => ["2011 Winter","2010-11"],
    "4420" => ["2011 Spring","2010-11"],
    "4430" => ["2011 Summer","2010-11"],

    "4440" => ["2011 Fall","2011-12"],
    "4445" => ["2011-2012 Academic Year","2011-12"],
    "4450" => ["2012 Winter","2011-12"],
    "4460" => ["2012 Spring","2011-12"],
    "4470" => ["2012 Summer","2011-12"],

    "4480" => ["2012 Fall","2012-13"],
    "4485" => ["2012-2013 Academic Year","2012-13"],
    "4490" => ["2013 Winter","2012-13"],
    "4500" => ["2013 Spring","2012-13"],
    "4510" => ["2013 Summer","2012-13"],

    "4520" => ["2013 Fall","2013-14"],
    "4525" => ["2013-2014 Academic Year","2013-14"],
    "4530" => ["2014 Winter","2013-14"],
    "4540" => ["2014 Spring","2013-14"],
    "4550" => ["2014 Winter", "2013-14"],

    "4560" => ["2014 Fall", "2014-15"],
    "4565" => ["2014-2015 Academic Year", "2014-15"],
    "4570" => ["2015 Winter", "2014-15"],
    "4580" => ["2015 Spring", "2014-15"],
    "4600" => ["2015 Winter", "2014-15"]
}

hash_terms.each { |key, value|
    Term.create :id => key, :title => value[0], :year => value[1]
}
